In [1]:
# Clean Data for Silver Layer
import pandas as pd
df = pd.read_csv("abfss://ws_SAP_GRC_Operation@onelake.dfs.fabric.microsoft.com/lh_SAP_GRC_Operation.Lakehouse/Files/raw_access_request.csv")
display(df)

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 3, Finished, Available, Finished, False)

SynapseWidget(Synapse.DataFrame, ea76721f-211c-4e69-b095-02f3a52a8f1e)

In [2]:
df.shape

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 4, Finished, Available, Finished, False)

(19225, 19)

In [3]:
df.info()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 5, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19225 entries, 0 to 19224
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   request_id                19225 non-null  object
 1   ticket_type_id            19225 non-null  object
 2   priority_id               19225 non-null  object
 3   system_id                 19190 non-null  object
 4   bu_id                     19225 non-null  object
 5   assigned_team_member_id   19225 non-null  object
 6   request_status            19225 non-null  object
 7   request_created_datetime  19225 non-null  object
 8   assignment_datetime       19225 non-null  object
 9   closure_datetime          19055 non-null  object
 10  queue_wait_hours          19225 non-null  float64
 11  user_info_wait_hours      19225 non-null  float64
 12  grc_approval_wait_hours   19225 non-null  float64
 13  fulfilment_hours          19225 non-null  float64
 14  closure_lag_hours         19225 non-null  float64
 15  total_resolution_hours    18881 non-null  float64
 16  is_sla_eligible           19225 non-null  int64
 17  sla_target_hours          19225 non-null  float64
 18  sla_status                19225 non-null  object
dtypes: float64(7), int64(1), object(11)
memory usage: 2.8+ MB

In [4]:
df.describe()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 6, Finished, Available, Finished, False)

,queue_wait_hours,user_info_wait_hours,grc_approval_wait_hours,fulfilment_hours,closure_lag_hours,total_resolution_hours,is_sla_eligible,sla_target_hours
count,19225.000000,19225.000000,19225.000000,19225.000000,19225.000000,18881.000000,19225.000000,19225.000000
mean,3.036776,2.775546,4.632750,2.101857,0.849270,13.316367,0.990949,265.144759
std,2.162159,9.595255,14.079772,1.617753,0.383557,17.292611,0.094706,126.446005
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.720000,0.000000,4.000000
25%,1.450000,0.000000,0.000000,0.920000,0.520000,4.730000,1.000000,336.000000
50%,2.550000,0.000000,0.000000,1.720000,0.850000,7.090000,1.000000,336.000000
75%,4.080000,0.000000,0.000000,2.890000,1.170000,12.870000,1.000000,336.000000
max,21.420000,165.420000,195.980000,12.660000,1.980000,272.280000,1.000000,336.000000

In [5]:
df.duplicated().value_counts()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 7, Finished, Available, Finished, False)

False    19200
True        25
Name: count, dtype: int64

In [6]:
df['request_id'].value_counts()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 8, Finished, Available, Finished, False)

request_id
REQ0000001    2
REQ0000002    2
REQ0000003    2
REQ0000004    2
REQ0000005    2
             ..
REQ0019196    1
REQ0019197    1
REQ0019198    1
REQ0019199    1
REQ0019200    1
Name: count, Length: 19200, dtype: int64

**Duplicate Detection**

In [7]:
# Drop duplicates, keeping the first occurrence.
df.drop_duplicates(subset='request_id',keep='first', inplace=True)

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 9, Finished, Available, Finished, False)

In [8]:
# Verify the final row count.
df.shape

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 10, Finished, Available, Finished, False)

(19200, 19)

In [9]:
df.duplicated().value_counts()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 11, Finished, Available, Finished, False)

False    19200
Name: count, dtype: int64

In [10]:
df.head(20)

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 12, Finished, Available, Finished, False)

,request_id,ticket_type_id,priority_id,system_id,bu_id,assigned_team_member_id,request_status,request_created_datetime,assignment_datetime,closure_datetime,queue_wait_hours,user_info_wait_hours,grc_approval_wait_hours,fulfilment_hours,closure_lag_hours,total_resolution_hours,is_sla_eligible,sla_target_hours,sla_status
0,REQ0000001,TT03,SR14,SYS05,BU03,TM102,Closed Complete,2024-03-12 21:20:20,2024-03-13 00:25:08,2024-03-13 04:56:56,3.08,0.37,0.00,3.67,0.49,7.61,1,336.0,SLA Met
1,REQ0000002,TT05,P3,SYS01,BU04,TM103,Closed Complete,2024-10-03 23:05:04,2024-10-03 23:10:28,2024-10-04 04:03:52,0.09,0.00,0.00,3.53,1.36,4.98,1,24.0,SLA Met
2,REQ0000003,TT01,SR14,SYS01,BU03,TM104,Closed Complete,2025-07-20 18:33:23,2025-07-20 21:17:47,2025-07-21 00:29:47,2.74,0.00,1.61,1.11,0.48,5.94,1,336.0,SLA Met
3,REQ0000004,TT07,P4,SYS04,BU01,TM102,Closed Complete,2024-12-11 18:55:48,2024-12-11 23:15:36,2024-12-13 08:33:36,4.33,32.24,0.00,0.60,0.46,37.63,1,120.0,SLA Met
4,REQ0000005,TT03,SR14,SYS01,BU04,TM103,Closed Complete,2024-01-02 18:29:17,2024-01-02 19:11:53,2024-01-04 10:02:17,0.71,0.00,35.81,2.06,0.97,39.55,1,336.0,SLA Met
5,REQ0000006,TT06,P1,SYS02,BU04,TM105,Assigned,2025-12-02 15:26:31,2025-12-02 18:29:31,NaN,3.05,0.00,26.34,1.69,0.00,NaN,1,4.0,Breached SLA (Open)
6,REQ0000007,TT07,P4,SYS02,BU05,TM105,Closed Complete,2024-02-10 10:34:04,2024-02-10 17:47:16,2024-02-10 21:10:40,7.22,0.00,0.00,2.75,0.64,10.61,1,120.0,SLA Met
7,REQ0000008,TT05,P3,SYS01,BU02,TM105,Closed Complete,2024-02-10 14:30:51,2024-02-10 19:09:15,2024-02-11 05:11:39,4.64,7.23,0.00,1.51,1.30,14.68,1,24.0,SLA Met
8,REQ0000009,TT04,SR14,SYS02,BU03,TM103,Closed Complete,2025-06-30 19:36:32,2025-06-30 21:23:56,2025-07-01 00:49:44,1.79,0.00,0.00,2.53,0.90,5.22,1,336.0,SLA Met
9,REQ0000010,TT02,SR14,SYS01,BU02,TM102,Closed Complete,2025-07-07 06:30:19,2025-07-07 10:42:55,2025-07-07 12:23:43,4.21,0.00,0.00,0.40,1.28,5.89,1,336.0,SLA Met
10,REQ0000011,TT07,P4,SYS01,BU05,TM105,Closed Complete,2025-10-16 09:23:47,2025-10-16 14:30:23,2025-10-16 18:27:23,5.11,0.00,0.00,3.00,0.95,9.06,1,120.0,SLA Met
11,REQ0000012,TT02,SR14,SYS01,BU04,TM103,Closed Complete,2024-01-28 19:12:43,2024-01-28 22:28:55,2024-01-29 12:17:31,3.27,7.06,3.13,3.04,0.58,17.08,1,336.0,SLA Met
12,REQ0000013,TT04,SR14,SYS01,BU05,TM103,Closed Complete,2024-09-15 16:07:33,2024-09-15 18:09:57,2024-09-16 02:03:57,2.04,0.00,6.03,1.31,0.56,9.94,1,336.0,SLA Met
13,REQ0000014,TT03,SR14,SYS02,BU01,TM102,Closed Complete,2025-11-22 15:06:24,2025-11-22 16:21:24,2025-11-22 20:04:00,1.25,0.00,0.00,3.24,0.47,4.96,1,336.0,SLA Met
14,REQ0000015,TT01,SR14,SYS05,BU03,TM102,Closed Complete,2024-04-22 00:14:14,2024-04-22 01:11:50,2024-04-22 03:14:14,0.96,0.00,0.00,1.05,0.99,3.00,1,336.0,SLA Met
15,REQ0000016,TT08,P2,SYS01,BU04,TM101,Closed Complete,2025-03-14 03:31:28,2025-03-14 05:17:40,2025-03-14 10:40:28,1.77,0.00,0.00,4.69,0.69,7.15,1,12.0,SLA Met
16,REQ0000017,TT03,SR14,SYS01,BU01,TM103,Closed Complete,2024-07-19 11:41:47,2024-07-19 12:20:47,2024-07-19 14:39:23,0.65,0.00,0.00,1.22,1.09,2.96,1,336.0,SLA Met
17,REQ0000018,TT04,SR14,SYS04,BU04,TM105,Closed Complete,2025-12-11 23:16:03,2025-12-12 03:49:39,2025-12-13 00:07:39,4.56,0.00,17.50,2.56,0.24,24.86,1,336.0,SLA Met
18,REQ0000019,TT02,SR14,SYS02,BU02,TM104,Closed Complete,2025-09-02 04:37:26,2025-09-02 09:23:02,2025-09-03 06:33:50,4.76,0.00,19.44,0.31,1.43,25.94,1,336.0,SLA Met
19,REQ0000020,TT06,P1,SYS04,BU03,TM103,Closed Complete,2024-01-09 02:03:20,2024-01-09 04:55:32,2024-01-09 08:27:20,2.87,0.00,0.00,2.82,0.71,6.40,1,4.0,SLA Breached

**String Trimming & Key Standardization**

In [11]:
# Stripping blank space
for col in ['request_id', 'ticket_type_id', 'priority_id', 'system_id', 'bu_id', 'assigned_team_member_id', 'request_status']:
    df[col].str.strip()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 13, Finished, Available, Finished, False)

In [12]:
df.head(20)

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 14, Finished, Available, Finished, False)

,request_id,ticket_type_id,priority_id,system_id,bu_id,assigned_team_member_id,request_status,request_created_datetime,assignment_datetime,closure_datetime,queue_wait_hours,user_info_wait_hours,grc_approval_wait_hours,fulfilment_hours,closure_lag_hours,total_resolution_hours,is_sla_eligible,sla_target_hours,sla_status
0,REQ0000001,TT03,SR14,SYS05,BU03,TM102,Closed Complete,2024-03-12 21:20:20,2024-03-13 00:25:08,2024-03-13 04:56:56,3.08,0.37,0.00,3.67,0.49,7.61,1,336.0,SLA Met
1,REQ0000002,TT05,P3,SYS01,BU04,TM103,Closed Complete,2024-10-03 23:05:04,2024-10-03 23:10:28,2024-10-04 04:03:52,0.09,0.00,0.00,3.53,1.36,4.98,1,24.0,SLA Met
2,REQ0000003,TT01,SR14,SYS01,BU03,TM104,Closed Complete,2025-07-20 18:33:23,2025-07-20 21:17:47,2025-07-21 00:29:47,2.74,0.00,1.61,1.11,0.48,5.94,1,336.0,SLA Met
3,REQ0000004,TT07,P4,SYS04,BU01,TM102,Closed Complete,2024-12-11 18:55:48,2024-12-11 23:15:36,2024-12-13 08:33:36,4.33,32.24,0.00,0.60,0.46,37.63,1,120.0,SLA Met
4,REQ0000005,TT03,SR14,SYS01,BU04,TM103,Closed Complete,2024-01-02 18:29:17,2024-01-02 19:11:53,2024-01-04 10:02:17,0.71,0.00,35.81,2.06,0.97,39.55,1,336.0,SLA Met
5,REQ0000006,TT06,P1,SYS02,BU04,TM105,Assigned,2025-12-02 15:26:31,2025-12-02 18:29:31,NaN,3.05,0.00,26.34,1.69,0.00,NaN,1,4.0,Breached SLA (Open)
6,REQ0000007,TT07,P4,SYS02,BU05,TM105,Closed Complete,2024-02-10 10:34:04,2024-02-10 17:47:16,2024-02-10 21:10:40,7.22,0.00,0.00,2.75,0.64,10.61,1,120.0,SLA Met
7,REQ0000008,TT05,P3,SYS01,BU02,TM105,Closed Complete,2024-02-10 14:30:51,2024-02-10 19:09:15,2024-02-11 05:11:39,4.64,7.23,0.00,1.51,1.30,14.68,1,24.0,SLA Met
8,REQ0000009,TT04,SR14,SYS02,BU03,TM103,Closed Complete,2025-06-30 19:36:32,2025-06-30 21:23:56,2025-07-01 00:49:44,1.79,0.00,0.00,2.53,0.90,5.22,1,336.0,SLA Met
9,REQ0000010,TT02,SR14,SYS01,BU02,TM102,Closed Complete,2025-07-07 06:30:19,2025-07-07 10:42:55,2025-07-07 12:23:43,4.21,0.00,0.00,0.40,1.28,5.89,1,336.0,SLA Met
10,REQ0000011,TT07,P4,SYS01,BU05,TM105,Closed Complete,2025-10-16 09:23:47,2025-10-16 14:30:23,2025-10-16 18:27:23,5.11,0.00,0.00,3.00,0.95,9.06,1,120.0,SLA Met
11,REQ0000012,TT02,SR14,SYS01,BU04,TM103,Closed Complete,2024-01-28 19:12:43,2024-01-28 22:28:55,2024-01-29 12:17:31,3.27,7.06,3.13,3.04,0.58,17.08,1,336.0,SLA Met
12,REQ0000013,TT04,SR14,SYS01,BU05,TM103,Closed Complete,2024-09-15 16:07:33,2024-09-15 18:09:57,2024-09-16 02:03:57,2.04,0.00,6.03,1.31,0.56,9.94,1,336.0,SLA Met
13,REQ0000014,TT03,SR14,SYS02,BU01,TM102,Closed Complete,2025-11-22 15:06:24,2025-11-22 16:21:24,2025-11-22 20:04:00,1.25,0.00,0.00,3.24,0.47,4.96,1,336.0,SLA Met
14,REQ0000015,TT01,SR14,SYS05,BU03,TM102,Closed Complete,2024-04-22 00:14:14,2024-04-22 01:11:50,2024-04-22 03:14:14,0.96,0.00,0.00,1.05,0.99,3.00,1,336.0,SLA Met
15,REQ0000016,TT08,P2,SYS01,BU04,TM101,Closed Complete,2025-03-14 03:31:28,2025-03-14 05:17:40,2025-03-14 10:40:28,1.77,0.00,0.00,4.69,0.69,7.15,1,12.0,SLA Met
16,REQ0000017,TT03,SR14,SYS01,BU01,TM103,Closed Complete,2024-07-19 11:41:47,2024-07-19 12:20:47,2024-07-19 14:39:23,0.65,0.00,0.00,1.22,1.09,2.96,1,336.0,SLA Met
17,REQ0000018,TT04,SR14,SYS04,BU04,TM105,Closed Complete,2025-12-11 23:16:03,2025-12-12 03:49:39,2025-12-13 00:07:39,4.56,0.00,17.50,2.56,0.24,24.86,1,336.0,SLA Met
18,REQ0000019,TT02,SR14,SYS02,BU02,TM104,Closed Complete,2025-09-02 04:37:26,2025-09-02 09:23:02,2025-09-03 06:33:50,4.76,0.00,19.44,0.31,1.43,25.94,1,336.0,SLA Met
19,REQ0000020,TT06,P1,SYS04,BU03,TM103,Closed Complete,2024-01-09 02:03:20,2024-01-09 04:55:32,2024-01-09 08:27:20,2.87,0.00,0.00,2.82,0.71,6.40,1,4.0,SLA Breached

In [13]:
# Uniform Column Names
df.columns = df.columns.str.replace("_"," ")
df.rename(columns=str.title, inplace=True)
df.rename(columns={'Bu Id':'BU Id','Is Sla Eligible':'SLA Eligiblity','Sla Target Hours':'SLA Target Hours', 'Sla Status':'SLA Status'}, inplace=True)
df.columns

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 15, Finished, Available, Finished, False)

Index(['Request Id', 'Ticket Type Id', 'Priority Id', 'System Id', 'BU Id',
       'Assigned Team Member Id', 'Request Status', 'Request Created Datetime',
       'Assignment Datetime', 'Closure Datetime', 'Queue Wait Hours',
       'User Info Wait Hours', 'Grc Approval Wait Hours', 'Fulfilment Hours',
       'Closure Lag Hours', 'Total Resolution Hours', 'SLA Eligiblity',
       'SLA Target Hours', 'SLA Status'],
      dtype='object')

In [14]:
df['Request Status'].unique()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 17, Finished, Available, Finished, False)

array(['Closed Complete', 'Assigned', 'Transferred', 'Cancelled',
       'Work in Progress', 'CLOSED COMPLETE', 'Pending User Info',
       'CANCELLED'], dtype=object)

In [15]:
df['Request Status'].str.strip().str.title().value_counts()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 19, Finished, Available, Finished, False)

Request Status
Closed Complete      18561
Cancelled              296
Transferred            174
Assigned                67
Work In Progress        57
Pending User Info       45
Name: count, dtype: int64

In [16]:
df['SLA Status'].unique()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 20, Finished, Available, Finished, False)

array(['SLA Met', 'Breached SLA (Open)', 'SLA Breached',
       'Not Applicable (Transferred)'], dtype=object)

**Missing / Null Handling & Quarantine Routing (Silver Pattern)**

In [17]:
df.isnull().sum()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 21, Finished, Available, Finished, False)

Request Id                    0
Ticket Type Id                0
Priority Id                   0
System Id                    35
BU Id                         0
Assigned Team Member Id       0
Request Status                0
Request Created Datetime      0
Assignment Datetime           0
Closure Datetime            169
Queue Wait Hours              0
User Info Wait Hours          0
Grc Approval Wait Hours       0
Fulfilment Hours              0
Closure Lag Hours             0
Total Resolution Hours      343
SLA Eligiblity                0
SLA Target Hours              0
SLA Status                    0
dtype: int64

In [18]:
# Filter these orphaned records into a separate DataFrame (df_quarantine_rejected) so they can be saved as a rejected table for audit analysis.
df_quarantine_rejected = df[df['System Id'].isnull()]
df_quarantine_rejected.to_csv('rejected_requests.csv')
df_quarantine_rejected

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 22, Finished, Available, Finished, False)

,Request Id,Ticket Type Id,Priority Id,System Id,BU Id,Assigned Team Member Id,Request Status,Request Created Datetime,Assignment Datetime,Closure Datetime,Queue Wait Hours,User Info Wait Hours,Grc Approval Wait Hours,Fulfilment Hours,Closure Lag Hours,Total Resolution Hours,SLA Eligiblity,SLA Target Hours,SLA Status
246,REQ0000247,TT03,SR14,NaN,BU01,TM105,Closed Complete,2025-09-04 21:02:54,2025-09-05 02:25:42,2025-09-05 05:59:54,5.38,0.00,0.00,2.18,1.39,8.95,1,336.0,SLA Met
412,REQ0000413,TT01,SR14,NaN,BU03,TM103,Closed Complete,2025-07-19 14:01:59,2025-07-19 20:43:23,2025-07-19 21:11:35,6.69,0.00,0.00,0.17,0.30,7.16,1,336.0,SLA Met
593,REQ0000594,TT05,P3,NaN,BU01,TM104,Closed Complete,2024-11-18 03:02:56,2024-11-18 04:55:08,2024-11-18 09:35:56,1.87,1.58,0.00,2.50,0.60,6.55,1,24.0,SLA Met
761,REQ0000762,TT03,SR14,NaN,BU01,TM104,Closed Complete,2024-12-01 03:00:46,2024-12-01 04:32:34,2024-12-01 07:51:10,1.53,0.00,0.00,2.12,1.19,4.84,1,336.0,SLA Met
1439,REQ0001440,TT03,SR14,NaN,BU01,TM103,Closed Complete,2024-03-02 22:37:07,2024-03-03 05:40:43,2024-03-03 22:20:55,7.06,1.04,12.61,1.87,1.15,23.73,1,336.0,SLA Met
2498,REQ0002499,TT08,P2,NaN,BU05,TM105,Closed Complete,2024-02-07 08:33:57,2024-02-07 10:45:57,2024-02-07 21:48:21,2.20,9.26,0.00,1.16,0.62,13.24,1,12.0,SLA Breached
3423,REQ0003424,TT03,SR14,NaN,BU04,TM105,Closed Complete,2024-10-02 00:00:11,2024-10-02 01:56:35,2024-10-02 03:19:59,1.94,0.00,0.00,0.47,0.92,3.33,1,336.0,SLA Met
3705,REQ0003706,TT05,P3,NaN,BU03,TM105,Closed Complete,2024-01-21 02:09:04,2024-01-21 04:36:04,2024-01-21 07:50:28,2.45,0.00,0.00,1.79,1.45,5.69,1,24.0,SLA Met
5679,REQ0005680,TT03,SR14,NaN,BU01,TM105,Closed Complete,2024-10-25 12:48:16,2024-10-25 13:45:52,2024-10-25 15:18:52,0.96,0.00,0.00,0.98,0.57,2.51,1,336.0,SLA Met
5833,REQ0005834,TT01,SR14,NaN,BU03,TM105,Cancelled,2025-07-07 21:23:40,2025-07-08 02:54:16,2025-07-08 16:27:16,5.51,11.96,0.00,0.20,1.39,19.06,1,336.0,SLA Met
6755,REQ0006756,TT03,SR14,NaN,BU01,TM105,Closed Complete,2025-06-19 20:04:50,2025-06-19 22:40:14,2025-06-20 16:55:50,2.59,0.00,14.21,3.58,0.47,20.85,1,336.0,SLA Met
7185,REQ0007186,TT07,P4,NaN,BU03,TM104,Closed Complete,2025-09-11 00:35:14,2025-09-11 00:55:38,2025-09-11 07:04:38,0.34,0.00,0.00,4.86,1.29,6.49,1,120.0,SLA Met
7244,REQ0007245,TT03,SR14,NaN,BU05,TM105,Closed Complete,2025-04-14 10:31:51,2025-04-14 12:48:03,2025-04-16 12:03:39,2.27,44.62,0.00,1.62,1.02,49.53,1,336.0,SLA Met
7918,REQ0007919,TT03,SR14,NaN,BU02,TM102,Closed Complete,2025-02-09 12:37:56,2025-02-09 17:22:20,2025-02-09 20:12:44,4.74,0.00,0.00,1.81,1.03,7.58,1,336.0,SLA Met
8072,REQ0008073,TT03,SR14,NaN,BU05,TM105,Closed Complete,2025-09-15 10:30:32,2025-09-15 12:35:20,2025-09-15 16:58:08,2.08,0.00,0.00,3.30,1.08,6.46,1,336.0,SLA Met
8075,REQ0008076,TT04,SR14,NaN,BU03,TM105,Closed Complete,2025-03-12 00:38:30,2025-03-12 07:50:30,2025-03-12 12:20:30,7.20,0.00,0.00,3.46,1.04,11.70,1,336.0,SLA Met
8481,REQ0008482,TT03,SR14,NaN,BU04,TM102,Closed Complete,2024-11-04 03:39:22,2024-11-04 05:24:22,2024-11-04 09:45:22,1.75,0.00,0.00,3.23,1.12,6.10,1,336.0,SLA Met
9181,REQ0009182,TT03,SR14,NaN,BU05,TM102,Closed Complete,2025-04-14 13:07:23,2025-04-14 17:48:47,2025-04-14 19:28:59,4.69,0.00,0.00,0.93,0.74,6.36,1,336.0,SLA Met
9207,REQ0009208,TT04,SR14,NaN,BU02,TM101,Closed Complete,2024-05-26 10:19:04,2024-05-26 14:07:04,2024-05-26 15:57:28,3.80,0.00,0.00,1.13,0.71,5.64,1,336.0,SLA Met
9588,REQ0009589,TT04,SR14,NaN,BU03,TM102,Closed Complete,2025-11-10 07:18:00,2025-11-10 08:10:12,2025-11-11 00:26:24,0.87,0.00,8.92,6.81,0.54,17.14,1,336.0,SLA Met
9772,REQ0009773,TT05,P3,NaN,BU03,TM105,Closed Complete,2025-09-25 00:03:59,2025-09-25 02:38:11,2025-09-25 04:57:59,2.57,0.00,0.00,1.79,0.54,4.90,1,24.0,SLA Met
9873,REQ0009874,TT03,SR14,NaN,BU02,TM104,Closed Complete,2025-04-02 19:11:08,2025-04-02 22:02:08,2025-04-02 23:55:32,2.85,0.00,0.00,1.47,0.42,4.74,1,336.0,SLA Met
11344,REQ0011345,TT03,SR14,NaN,BU02,TM104,Closed Complete,2024-07-17 20:17:14,2024-07-18 00:23:50,2024-07-18 07:10:38,4.11,0.00,0.53,5.42,0.83,10.89,1,336.0,SLA Met
12770,REQ0012771,TT03,SR14,NaN,BU05,TM103,Closed Complete,2024-11-02 18:51:40,2024-11-02 21:12:40,2024-11-02 23:48:40,2.35,0.00,0.00,2.18,0.42,4.95,1,336.0,SLA Met
13476,REQ0013477,TT02,SR14,NaN,BU05,TM105,Closed Complete,2024-10-07 20:33:49,2024-10-07 21:51:13,2024-10-08 18:10:25,1.29,0.00,17.04,2.49,0.79,21.61,1,336.0,SLA Met
14297,REQ0014298,TT03,SR14,NaN,BU05,TM104,Work in Progress,2025-12-03 16:08:41,2025-12-03 18:17:41,NaN,2.15,0.00,27.08,3.58,0.00,NaN,1,336.0,Breached SLA (Open)
14844,REQ0014845,TT01,SR14,NaN,BU04,TM103,Closed Complete,2024-03-18 08:59:12,2024-03-18 11:06:24,2024-03-18 12:51:24,2.12,0.00,0.00,0.94,0.81,3.87,1,336.0,SLA Met
15064,REQ0015065,TT03,SR14,NaN,BU02,TM104,Closed Complete,2025-04-09 17:22:17,2025-04-09 22:04:53,2025-04-11 17:03:05,4.71,0.00,39.19,2.38,1.40,47.68,1,336.0,SLA Met
15454,REQ0015455,TT03,SR14,NaN,BU04,TM102,Closed Complete,2024-07-01 01:42:03,2024-07-01 05:52:51,2024-07-01 08:54:39,4.18,0.00,0.00,2.40,0.63,7.21,1,336.0,SLA Met
15705,REQ0015706,TT05,P3,NaN,BU04,TM102,Closed Complete,2025-01-03 16:27:41,2025-01-03 20:14:29,2025-01-03 21:45:41,3.78,0.00,0.00,0.95,0.57,5.30,1,24.0,SLA Met
15935,REQ0015936,TT03,SR14,NaN,BU03,TM103,Closed Complete,2025-12-28 18:40:35,2025-12-28 21:00:59,2025-12-28 23:30:59,2.34,0.00,0.00,1.35,1.15,4.84,1,336.0,SLA Met
16400,REQ0016401,TT06,P1,NaN,BU01,TM102,Closed Complete,2024-12-21 22:54:52,2024-12-22 02:18:52,2024-12-22 04:22:28,3.40,0.00,0.00,1.36,0.70,5.46,1,4.0,SLA Breached
16573,REQ0016574,TT07,P4,NaN,BU01,TM102,Closed Complete,2025-02-16 03:18:08,2025-02-16 08:13:20,2025-02-16 11:49:20,4.92,0.00,0.00,2.24,1.36,8.52,1,120.0,SLA Met
18264,REQ0018265,TT01,SR14,NaN,BU01,TM103,Closed Complete,2025-03-05 07:38:05,2025-03-05 10:21:53,2025-03-05 12:37:29,2.73,0.00,0.00,1.20,1.06,4.99,1,336.0,SLA Met
18504,REQ0018505,TT04,SR14,NaN,BU01,TM102,Closed Complete,2024-07-04 08:30:39,2024-07-04 12:37:51,2024-07-04 14:33:03,4.12,0.00,0.00,1.22,0.70,6.04,1,336.0,SLA Met

In [19]:
df = df[df['System Id'].notnull()]
df.isnull().sum()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 23, Finished, Available, Finished, False)

Request Id                    0
Ticket Type Id                0
Priority Id                   0
System Id                     0
BU Id                         0
Assigned Team Member Id       0
Request Status                0
Request Created Datetime      0
Assignment Datetime           0
Closure Datetime            168
Queue Wait Hours              0
User Info Wait Hours          0
Grc Approval Wait Hours       0
Fulfilment Hours              0
Closure Lag Hours             0
Total Resolution Hours      342
SLA Eligiblity                0
SLA Target Hours              0
SLA Status                    0
dtype: int64

In [20]:
transferred_tasks = df[df['SLA Eligiblity']==0]
transferred_tasks

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 24, Finished, Available, Finished, False)

,Request Id,Ticket Type Id,Priority Id,System Id,BU Id,Assigned Team Member Id,Request Status,Request Created Datetime,Assignment Datetime,Closure Datetime,Queue Wait Hours,User Info Wait Hours,Grc Approval Wait Hours,Fulfilment Hours,Closure Lag Hours,Total Resolution Hours,SLA Eligiblity,SLA Target Hours,SLA Status
96,REQ0000097,TT05,P3,SYS02,BU01,TM105,Transferred,2024-01-12 00:22:21,2024-01-12 01:53:33,2024-01-12 03:46:51,1.52,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)
272,REQ0000273,TT07,P4,SYS04,BU05,TM104,Transferred,2025-08-30 20:45:07,2025-08-31 04:03:07,2025-08-31 05:44:12,7.30,0.0,0.0,0.0,0.5,NaN,0,120.0,Not Applicable (Transferred)
308,REQ0000309,TT08,P2,SYS01,BU03,TM104,Transferred,2025-01-11 21:05:45,2025-01-12 00:54:57,2025-01-12 01:52:04,3.82,0.0,0.0,0.0,0.5,NaN,0,12.0,Not Applicable (Transferred)
452,REQ0000453,TT05,P3,SYS02,BU04,TM104,Transferred,2025-07-02 15:47:07,2025-07-02 17:08:07,2025-07-02 18:20:49,1.35,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)
456,REQ0000457,TT05,P3,SYS01,BU04,TM105,Transferred,2025-06-02 08:39:46,2025-06-02 10:40:58,2025-06-02 12:36:18,2.02,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18786,REQ0018787,TT05,P3,SYS03,BU04,TM105,Transferred,2025-02-11 16:40:30,2025-02-11 19:42:18,2025-02-11 20:33:28,3.03,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)
18929,REQ0018930,TT05,P3,SYS03,BU03,TM102,Transferred,2025-04-23 13:01:07,2025-04-23 13:09:31,2025-04-23 14:50:21,0.14,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)
19052,REQ0019053,TT05,P3,SYS02,BU04,TM103,Transferred,2025-04-02 10:03:10,2025-04-02 12:15:46,2025-04-02 13:51:55,2.21,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)
19128,REQ0019129,TT05,P3,SYS02,BU02,TM103,Transferred,2025-04-27 21:56:17,2025-04-28 00:53:53,2025-04-28 02:29:26,2.96,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)
19189,REQ0019190,TT05,P3,SYS05,BU03,TM102,Transferred,2024-05-26 04:04:54,2024-05-26 05:43:54,2024-05-26 07:18:45,1.65,0.0,0.0,0.0,0.5,NaN,0,24.0,Not Applicable (Transferred)

In [21]:
df = df[df['SLA Eligiblity']==1]
df.shape

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 25, Finished, Available, Finished, False)

(18991, 19)

**Datetime Parsing & Format Validation**

In [22]:
df[df['Closure Datetime'].isnull()].shape

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 26, Finished, Available, Finished, False)

(168, 19)

In [23]:
df[df['Total Resolution Hours'].isnull() & df['SLA Eligiblity']==1].shape

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 27, Finished, Available, Finished, False)

(168, 19)

In [24]:
df.shape
# Correct filter for closure >= assignment
df[df['Closure Datetime'] >= df['Assignment Datetime']].shape

# ✅ Sanity check conditions
df[
    (df['Assignment Datetime'] >= df['Request Created Datetime']) &
    (df['Closure Datetime'].notna()) &
    (df['Closure Datetime'] >= df['Assignment Datetime'])
].shape

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 28, Finished, Available, Finished, False)

(18823, 19)

In [25]:
df.info()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 29, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
Index: 18991 entries, 0 to 19199
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Request Id                18991 non-null  object
 1   Ticket Type Id            18991 non-null  object
 2   Priority Id               18991 non-null  object
 3   System Id                 18991 non-null  object
 4   BU Id                     18991 non-null  object
 5   Assigned Team Member Id   18991 non-null  object
 6   Request Status            18991 non-null  object
 7   Request Created Datetime  18991 non-null  object
 8   Assignment Datetime       18991 non-null  object
 9   Closure Datetime          18823 non-null  object
 10  Queue Wait Hours          18991 non-null  float64
 11  User Info Wait Hours      18991 non-null  float64
 12  Grc Approval Wait Hours   18991 non-null  float64
 13  Fulfilment Hours          18991 non-null  float64
 14  Closure Lag Hours         18991 non-null  float64
 15  Total Resolution Hours    18823 non-null  float64
 16  SLA Eligiblity            18991 non-null  int64
 17  SLA Target Hours          18991 non-null  float64
 18  SLA Status                18991 non-null  object
dtypes: float64(7), int64(1), object(11)
memory usage: 2.9+ MB

In [26]:
# Changing the Data Type to Date Time for specific columns
for col in {'Request Created Datetime', 'Assignment Datetime', 'Closure Datetime'}:
    df[col] = pd.to_datetime(df[col])

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 30, Finished, Available, Finished, False)

**Numeric Duration Validation**

In [27]:
for col in ['Queue Wait Hours','User Info Wait Hours',
            'Grc Approval Wait Hours','Fulfilment Hours',
            'Closure Lag Hours','Total Resolution Hours']:
    count_neg = (df[col] < 0.0).sum()
    if count_neg > 0:
        print(f"{col}: {count_neg} negative values")
else:
        print("No Negetives")

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 31, Finished, Available, Finished, False)

No Negetives

In [28]:
df['Request Status'].unique()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 32, Finished, Available, Finished, False)

array(['Closed Complete', 'Assigned', 'Cancelled', 'Work in Progress',
       'CLOSED COMPLETE', 'Pending User Info', 'CANCELLED'], dtype=object)

**Verifying Referential Integrity (Dimension Joins)**

In [29]:
# Conceptual check:
df_ticket_type = pd.read_csv("abfss://ws_SAP_GRC_Operation@onelake.dfs.fabric.microsoft.com/lh_SAP_GRC_Operation.Lakehouse/Files/dim_ticket_type.csv")
set(df['Ticket Type Id']) - set(df_ticket_type['ticket_type_id'])

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 33, Finished, Available, Finished, False)

set()

In [30]:
# Conceptual check:
df_team_member = pd.read_csv("abfss://ws_SAP_GRC_Operation@onelake.dfs.fabric.microsoft.com/lh_SAP_GRC_Operation.Lakehouse/Files/dim_team_member.csv")
set(df['Assigned Team Member Id']) - set(df_team_member['team_member_id'])

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 34, Finished, Available, Finished, False)

set()

In [31]:
# Conceptual check:
df_system_type = pd.read_csv("abfss://ws_SAP_GRC_Operation@onelake.dfs.fabric.microsoft.com/lh_SAP_GRC_Operation.Lakehouse/Files/dim_system.csv")
set(df['System Id']) - set(df_system_type['system_id'])

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 35, Finished, Available, Finished, False)

set()

In [32]:
# Conceptual check:
df_priority = pd.read_csv("abfss://ws_SAP_GRC_Operation@onelake.dfs.fabric.microsoft.com/lh_SAP_GRC_Operation.Lakehouse/Files/dim_priority.csv")
set(df['Priority Id']) - set(df_priority['priority_id'])

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 36, Finished, Available, Finished, False)

set()

In [33]:
# Conceptual check:
df_BU_type = pd.read_csv("abfss://ws_SAP_GRC_Operation@onelake.dfs.fabric.microsoft.com/lh_SAP_GRC_Operation.Lakehouse/Files/dim_business_unit.csv")
set(df['BU Id']) - set(df_BU_type['bu_id'])

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 37, Finished, Available, Finished, False)

set()

In [34]:
df.info()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 38, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
Index: 18991 entries, 0 to 19199
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Request Id                18991 non-null  object
 1   Ticket Type Id            18991 non-null  object
 2   Priority Id               18991 non-null  object
 3   System Id                 18991 non-null  object
 4   BU Id                     18991 non-null  object
 5   Assigned Team Member Id   18991 non-null  object
 6   Request Status            18991 non-null  object
 7   Request Created Datetime  18991 non-null  datetime64[ns]
 8   Assignment Datetime       18991 non-null  datetime64[ns]
 9   Closure Datetime          18823 non-null  datetime64[ns]
 10  Queue Wait Hours          18991 non-null  float64
 11  User Info Wait Hours      18991 non-null  float64
 12  Grc Approval Wait Hours   18991 non-null  float64
 13  Fulfilment Hours          18991 non-null  float64
 14  Closure Lag Hours         18991 non-null  float64
 15  Total Resolution Hours    18823 non-null  float64
 16  SLA Eligiblity            18991 non-null  int64
 17  SLA Target Hours          18991 non-null  float64
 18  SLA Status                18991 non-null  object
dtypes: datetime64[ns](3), float64(7), int64(1), object(8)
memory usage: 2.9+ MB

In [35]:
df.describe()

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 39, Finished, Available, Finished, False)

,Request Created Datetime,Assignment Datetime,Closure Datetime,Queue Wait Hours,User Info Wait Hours,Grc Approval Wait Hours,Fulfilment Hours,Closure Lag Hours,Total Resolution Hours,SLA Eligiblity,SLA Target Hours
count,18991,18991,18823,18991.000000,18991.000000,18991.000000,18991.000000,18991.000000,18823.000000,18991.0,18991.000000
mean,2024-12-30 12:39:45.174766848,2024-12-30 15:41:49.795692800,2024-12-27 22:45:36.935610880,3.034617,2.803360,4.677752,2.121005,0.852575,13.322749,1.0,267.174978
min,2024-01-01 00:12:56,2024-01-01 06:32:27,2024-01-01 08:04:15,0.010000,0.000000,0.000000,0.010000,0.000000,0.720000,1.0,4.000000
25%,2024-06-28 23:46:04.500000,2024-06-29 02:06:18,2024-06-27 17:55:22.500000,1.450000,0.000000,0.000000,0.940000,0.530000,4.720000,1.0,336.000000
50%,2024-12-31 00:18:22,2024-12-31 02:18:28,2024-12-28 20:54:15,2.540000,0.000000,0.000000,1.730000,0.860000,7.090000,1.0,336.000000
75%,2025-07-02 07:53:32,2025-07-02 09:52:34,2025-06-28 16:55:40,4.080000,0.000000,0.000000,2.900000,1.180000,12.870000,1.0,336.000000
max,2025-12-31 23:07:56,2026-01-01 00:34:15,2026-01-05 05:53:02,21.420000,165.420000,195.980000,12.660000,1.980000,272.280000,1.0,336.000000
std,NaN,NaN,NaN,2.163485,9.641791,14.150178,1.613336,0.383876,17.308925,0.0,125.198533

In [36]:
df.shape

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 40, Finished, Available, Finished, False)

(18991, 19)

In [37]:
# Converting the fact table to delta table
# Rename columns
df.columns = [col.strip().replace(" ", "_") for col in df.columns]

# Convert to Spark DataFrame
spark_df = spark.createDataFrame(df)

# Save to Silver layer
spark_df.write \
    .format("delta") \
    .mode("overwrite") \
    .save("Tables/Silver/operational_request")

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 41, Finished, Available, Finished, False)

In [38]:
# Converting the transferred_tasks table to delta table
# Rename columns
transferred_tasks.columns = [col.strip().replace(" ", "_") for col in transferred_tasks.columns]

# Convert to Spark DataFrame
spark_transferred_tasks = spark.createDataFrame(transferred_tasks)

# Save to Silver layer
spark_transferred_tasks.write \
    .format("delta") \
    .mode("overwrite") \
    .save("Tables/Silver/transferred_tasks")

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 42, Finished, Available, Finished, False)

In [39]:
# Converting the quarantine_rejected table to delta table
# Rename columns
df_quarantine_rejected.columns = [col.strip().replace(" ", "_") for col in df_quarantine_rejected.columns]

# Convert to Spark DataFrame
spark_quarantine_rejected = spark.createDataFrame(df_quarantine_rejected)

# Save to Silver layer
spark_quarantine_rejected.write \
    .format("delta") \
    .mode("overwrite") \
    .save("Tables/Silver/quarantine_rejected_tasks")

StatementMeta(, 6d2cbdf2-a043-45bb-a102-35932a47bf7a, 43, Finished, Available, Finished, False)